{-
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
-}

import Common

main :: IO ()
main = do
  putStr "P002: "
  print $ p002 4000000

-- 通常のフィボナッチ数列は初項と第2項が1,1だが今回は1,2になっていることに注意
fib12 :: [Int]
fib12 = drop 2 Common.fib

p002 :: Int -> Int
p002 = sum . filter even . flip takeWhile fib12 . (>)
